baseurl = "https://junhyukso.github.io"
languageCode = "ko-kr"
defaultContentLanguage = "ko"
theme = "hello-friend"
paginate = 5

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5
  # Enable to show reading time in minutes for posts
  toc = true
  showReadingTime = true
  lastModDisplay = ["Modified"]
  


[languages]
  [languages.ko]
    title = "Junhyuk So's Blog"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    lastModDisplay = "Modified:"

    [languages.ko.params.logo]
      logoText = "Junhyuk So's Blog"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.ko.menu]
      [[languages.ko.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.ko.menu.main]]
        identifier = "tag"
        name = "Tags"
        url = "/tags"
      [[languages.ko.menu.main]]
        identifier = "Archive"
        name = "Archive"
        url = "/archive"
